// DO NOT EDIT. This file is generated by litdoc.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import lit from "litdoc/lit.ts";
import * as $1 from "./docs/examples/multi-page/contact.ts";
import * as $2 from "./docs/examples/multi-page/index.ts";
import * as $3 from "./docs/examples/multi-page/sitemap.ts";
import * as $4 from "./docs/examples/single-page/index.ts";
import * as $5 from "./docs/features/cards.tsx";
import * as $6 from "./docs/features/headings.tsx";
import * as $7 from "./docs/features/icons.tsx";
import * as $9 from "./docs/features/links.tsx";
import * as $10 from "./docs/features/lists.tsx";
import * as $11 from "./docs/features/tags.tsx";
import * as $12 from "./docs/features/templates.tsx";

export const doc = lit({
  url: import.meta.url,
  root: "docs",
  assets: {
    "./docs/dev.md": 0,
    "./docs/examples/multi-page/contact.ts": $1,
    "./docs/examples/multi-page/index.ts": $2,
    "./docs/examples/multi-page/sitemap.ts": $3,
    "./docs/examples/single-page/index.ts": $4,
    "./docs/features/cards.tsx": $5,
    "./docs/features/headings.tsx": $6,
    "./docs/features/icons.tsx": $7,
    "./docs/features/linking/index.md": 8,
    "./docs/features/links.tsx": $9,
    "./docs/features/lists.tsx": $10,
    "./docs/features/tags.tsx": $11,
    "./docs/features/templates.tsx": $12,
    "./docs/features/tokens.md": 13,
    "./docs/index.md": 14,
  },
});
