// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./islands/feature_header.tsx";
import * as $1 from "./islands/feature.tsx";
import * as $2 from "./islands/header.tsx";
import * as $3 from "./islands/home_header.tsx";
import * as $4 from "./routes/_app.tsx";
import * as $5 from "./routes/_middleware.ts";
import * as $6 from "./routes/[...path].tsx";
import * as $7 from "./routes/index.tsx";

export default {
  config,
  baseUrl: import.meta.url,
  routes: {
    "./routes/_app.tsx": $4,
    "./routes/_middleware.ts": $5,
    "./routes/[...path].tsx": $6,
    "./routes/index.tsx": $7,
  },
  islands: {
    "./islands/feature_header.tsx": $0,
    "./islands/feature.tsx": $1,
    "./islands/header.tsx": $2,
    "./islands/home_header.tsx": $3,
  },
};
