// DO NOT EDIT. This file is generated by litdoc.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./features/litdoc/docs/cards.tsx";
import * as $1 from "./features/litdoc/docs/headings.tsx";
import * as $2 from "./features/litdoc/docs/icons.tsx";
import * as $3 from "./features/litdoc/docs/links.tsx";
import * as $4 from "./features/litdoc/docs/lists.tsx";
import * as $5 from "./features/litdoc/docs/lit.tsx";
import * as $6 from "./features/litdoc/docs/templates.tsx";
import * as $7 from "./features/litdoc/index.tsx";
import * as $8 from "./features/monaco/index.tsx";
import * as $9 from "./index.tsx";
import * as $10 from "./routes/index.tsx";

export default {
  baseUrl: import.meta.url,
  routes: {
    "./features/litdoc/docs/cards.tsx": $0,
    "./features/litdoc/docs/headings.tsx": $1,
    "./features/litdoc/docs/icons.tsx": $2,
    "./features/litdoc/docs/links.tsx": $3,
    "./features/litdoc/docs/lists.tsx": $4,
    "./features/litdoc/docs/lit.tsx": $5,
    "./features/litdoc/docs/templates.tsx": $6,
    "./features/litdoc/index.tsx": $7,
    "./features/monaco/index.tsx": $8,
    "./index.tsx": $9,
    "./routes/index.tsx": $10,
  },
};
