import { ensureMinDenoVersion } from "$fresh/src/dev/mod.ts";
import * as Manifest from "../manifest/mod.ts";

/** HELPERS **/

type Sync<T> = T extends Promise<infer R> ? R : never;
type Props = Sync<ReturnType<typeof collect>>;

async function collect(baseUrl: URL) {
  const patterns = {
    islands: /\/islands\/.*\.tsx?$/,
    routes: /\/routes\/.*\.tsx?$/,
  };

  return await Manifest.collect(baseUrl, {
    all: {
      match: [
        patterns.islands,
        patterns.routes,
      ],
    },
    routes: {
      includeFiles: true,
      match: [
        patterns.routes,
      ],
    },
    islands: {
      match: [
        patterns.islands,
      ],
    },
  });
}

const template = Manifest.tag<Props>`
// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running \`dev.ts\`.

import config from "./deno.json" assert { type: "json" };
${((props) =>
  Manifest.toEntries(props.all)
    .map((file) => `import * as ${file.varName} from "./${file.path}";`))}

export default {
  config,
  baseUrl: import.meta.url,
  routes: {
    ${(props) =>
  Manifest.toEntries(props.routes)
    .map((file) => `"./${file.path}": ${file.varName},`)}
  },
  islands: {
    ${(props) =>
  Manifest.toEntries(props.islands)
    .map((file) => `"./${file.path}": ${file.varName},`)}
  },
};
`;

/** MAIN **/

export async function dev(metaUrl: string, entryPoint: string) {
  ensureMinDenoVersion();

  const baseUrl = new URL("./", metaUrl);
  const mainUrl = new URL(entryPoint, baseUrl);

  const props = await collect(baseUrl);
  const raw = Manifest.stringify(template, props);

  const formatted = await Manifest.format(raw);
  await Manifest.write("fresh.gen.ts", formatted);

  console.log(
    `%cThe manifest has been generated for ` +
      `${props.routes.ids.length} routes ` +
      `and ${props.islands.ids.length} islands.`,
    "color: blue; font-weight: bold",
  );

  await import(mainUrl.href);
}
