import * as Manifest from "../manifest/mod.ts";

/** HELPERS **/

type Sync<T> = T extends Promise<infer R> ? R : never;
type Props = Sync<ReturnType<typeof collect>>;

async function collect(baseUrl: URL) {
  const patterns = {
    routes: /\/features\/[^/]+\/index\.tsx?$/,
  };

  return await Manifest.collect(baseUrl, {
    all: {
      match: [
        patterns.routes,
      ],
    },
    routes: {
      includeFiles: true,
      match: [
        patterns.routes,
      ],
    },
  });
}

const template = Manifest.tag<Props>`
// DO NOT EDIT. This file is generated by @lambda-ui/litdoc.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running \`dev.ts\`.

${((props) =>
  Manifest.toEntries(props.all)
    .map((file) => `import * as ${file.varName} from "./${file.path}";`))}

export default {
  baseUrl: import.meta.url,
  routes: {
    ${(props) =>
  Manifest.toEntries(props.routes)
    .map((file) => `"./${file.path}": ${file.varName},`)}
  },
};
`;

/** MAIN **/

export async function dev(metaUrl: string) {
  const baseUrl = new URL("./", metaUrl);

  const props = await collect(baseUrl);
  const raw = Manifest.stringify(template, props);

  const formatted = await Manifest.format(raw);
  await Manifest.write("litdoc.gen.ts", formatted);

  console.log(
    `%cThe manifest has been generated for ` +
      `${props.routes.ids.length} routes.`,
    "color: green; font-weight: bold",
  );
}
